[package]
name = "ebisu"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
poise = "0.6.1"
rhai = { version = "1.23.4", features = ["sync"] }
rosu-v2 = "0.11.0"
serenity = "0.12.4"
tokio = { version = "1", features = ["rt-multi-thread"] }
